# Create Sensor
POST http://127.0.0.1:8000/api/sensors/
Content-Type: application/json

{
  "name": "Лоджия",
  "description": "Датчик на лоджии"
}

###
# Update Sensor
PATCH http://127.0.0.1:8000/api/sensors/1/
Content-Type: application/json

{
  "description": "Датчик перенесен в спальню"
}

###

# Get Sensors List
GET http://127.0.0.1:8000/api/sensors/
Content-Type: application/json

###

# Get Sensor Detail
GET http://127.0.0.1:8000/api/sensors/detail/1/
Content-Type: application/json

###

# Create Measurement
POST http://127.0.0.1:8000/api/measurements/
Content-Type: application/json

{
  "sensor": 1,
  "temperature": 25.5
}

###